/*
 * QUANTCONNECT.COM - Democratizing Finance, Empowering Individuals.
 * Lean Algorithmic Trading Engine v2.0. Copyright 2014 QuantConnect Corporation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

namespace QuantConnect.Orders;

/// <summary>
/// Contains additional properties and settings for Gate.io orders
/// </summary>
public class GateOrderProperties : OrderProperties
{
    /// <summary>
    /// Post-only order (maker-only, no taker fee).
    /// If part of the order results in taking liquidity rather than providing,
    /// it will be rejected and no part of the order will execute.
    /// Note: this flag is only applied to Limit orders.
    /// </summary>
    public bool PostOnly { get; set; }

    /// <summary>
    /// Reduce-only order for futures contracts.
    /// This flag will ensure your position can only reduce in size if the order is triggered.
    /// It bypasses margin checks for position-closing orders.
    /// <seealso href="https://www.gate.io/docs/developers/apiv4/en/#futures-order"/>
    /// </summary>
    public bool? ReduceOnly { get; set; }

    /// <summary>
    /// Enable automatic borrowing for margin/cross-margin trading.
    /// If set to true, the system will automatically borrow insufficient amount if balance is not enough.
    /// Interest accrual begins immediately upon automatic borrowing.
    /// <seealso href="https://www.gate.io/docs/developers/apiv4/en/#create-an-order"/>
    /// </summary>
    public bool AutoBorrow { get; set; }

    /// <summary>
    /// Enable automatic repayment for automatic borrow loan generated by cross margin order.
    /// Default is disabled. This field is only effective for cross margin orders.
    /// Margin account does not support setting auto repayment for orders.
    /// <seealso href="https://www.gate.io/docs/developers/apiv4/en/#create-an-order"/>
    /// </summary>
    public bool AutoRepay { get; set; }

    /// <summary>
    /// Price buffer percentage for Spot market buy orders when converting to FOK (Fill-or-Kill) limit orders.
    /// Gate.io Spot market buy orders are denominated in quote currency (USDT), which conflicts with LEAN's
    /// base currency semantics. To maintain execution quantity precision, market buy orders are converted to
    /// FOK limit orders with a calculated limit price based on order book depth.
    ///
    /// This buffer is applied to the calculated weighted average price to ensure immediate execution.
    /// For example, 0.02 means the limit price will be set 2% above the calculated price.
    ///
    /// Default: 0.02 (2%)
    /// Range: 0.0 to 1.0 (0% to 100%)
    ///
    /// Note: Market sell orders are not affected as they already use base currency quantity.
    /// </summary>
    public decimal MarketOrderPriceBuffer { get; set; } = 0.02m;
}
